config/routes.rb
Cms::Application.routes.draw do

  mount Books::Engine, :at => "/books"
  match '/feed' => 'blogs#feed', :as => :feed, :defaults => { :format => 'atom' }
  get 'ebook' => 'ebooks#txt'
  get 'query_user_columns' => 'columns#query_user_columns'
  match 'update_user_columns' => 'columns#update_user_columns'
  get 'query_article_editors' => 'columns#query_article_editors'
  get 'query_recommend_users' => 'recommend#query_recommend_users'
  get 'chat' => 'chats#index'

  resources :renjoys, :enjoys, :chats

  match 'groups/update_byuser' => 'groups#update_byuser'
  get 'about' => 'groups#about'
  
  get ':id' => 'boards#show', :constraints => { :id => /\d+/ }
  get ':id/members' => 'boards#members', :constraints => { :id => /\d+/ }
  get 'p/:id' => 'posts#show'
  get 'idols/:name' => 'idols#show'
  get 'my_posts' => 'posts#my'
  get 'my_reply' => 'posts#my_reply'
  get 'bbs' => 'posts#bbs'
  get 'bbs/reply' => 'posts#reply'
  get 'commented' => 'comments#commented'
  get 'comments' => 'comments#comments'
  get 'update_user_comments_count'  => 'comments#update_user_comments_count'
  get 'update_group_users_count'  => 'groups#update_group_users_count'
  get 'update_users_clicks_count'  => 'users#update_users_clicks_count'
  get 'update_user_schools_split'  => 'users#update_user_schools_split'

  get 'archives' => 'archives#index'
  get 'archives/:month' => 'archives#month', :constraints => { :id => /\d+/ }
  
  get 'send_a_letter_to_:domain' => 'letters#new'
  get 'send_a_letter' => 'letters#new_simple'
  get 'letters/sent' => 'letters#sent'
  get 'letters/received' => 'letters#received'
  get 'as_a_writer' => 'users#as_a_writer'
  get 'signature' => 'users#signature'
  get 'edit_domain' => 'users#edit_domain'

  get 'zjtraces' => 'traces#index'
  get 'start_trace' => 'traces#start'
  get 'traces/start_trace_sina_user_one_list' => 'traces#start_trace_sina_user_one_list'
  get 'traces/start_trace_sina_user_all_list' => 'traces#start_trace_sina_user_all_list'
  get 'traces/start_trace_sina_user_two_list' => 'traces#start_trace_sina_user_two_list'
  get 'traces/start_trace_sina_users_latest_blogs' => 'traces#start_trace_sina_users_latest_blogs'
  get 'traces/clear_user_blogs' => 'traces#clear_user_blogs'

  get 's' => 'search#index'
  get 's/blogs/:title' => 'search#blogs'
  get 's/blogs' => 'search#index'
  get 's/:title' => 'search#all'

  get 'drafts' => 'drafts#index'
  get 'init_emotions' => 'emotions#init'

  get 'group_index' => 'groups#group_index'
  get 'groups/add_user_by_super'
  match 'groups/do_add_user_by_super' => 'groups#do_add_user_by_super'
  get 'groups/assign_admin'
  match 'assign_group_admin' => 'groups#do_assign_admin'
  get 'send_group_invitation' => 'groups#send_invitation'
  match 'do_send_invitation' => 'groups#do_send_invitation'
  match 'accept_group_invitation' => 'groups#accept_invitation'
  match 'gads/new'  => 'gads#new'

  resources :posts, :notes, :blogs, :follows, :memoirs, :albums, :idols, :hobbies, :customizes, :letters, :menus, :schoolnames, :messages, :groups, :gads

  resources :roles do
    member do
      get 'assign_menus'
      match 'do_assign_menus'
    end
  end

  get 'users/top'
  get 'users/recommended'
  get 'users/comments'
  match 'update_bind' => 'users#update_bind'
  resources :users do
    member do
      get 'assign_roles'
      match 'do_assign_roles'
    end
  end

  resources :columns do
    member do
      get 'up'
      get 'down'
    end
  end

  get 'column_blogs' => 'columnblogs#index'

  resources :gcolumns do
    member do
      get 'up'
      get 'down'
    end
  end

  resources :categories do
    member do
      get 'up'
      get 'down'
    end
  end

  resources :notecates do
    member do
      get 'up'
      get 'down'
    end
  end

  resources :assortments do
    member do
      get 'up'
      get 'down'
    end
  end

  resources :boards do
    member do
      get 'follow'
    end
  end

  resources :albums do
    resources :photos do
      resources :photocomments
    end
  end

  resources :photos do
    resources :photocomments
  end

  resources :notes do
    member do
      get 'assign_columns'
      match 'do_assign_columns'
      get 'assign_gcolumns'
      match 'do_assign_gcolumns'
    end
    resources :notecomments
  end
  
  resources :blogs do
    member do
      get 'assign_columns'
      match 'do_assign_columns'
      get 'assign_gcolumns'
      match 'do_assign_gcolumns'
    end
    resources :blogcomments
  end
  get 'm_reply_blogcomment/:comment_id' => 'blogcomments#m_reply'
  get 'm_reply_notecomment/:comment_id' => 'notecomments#m_reply'
  match 'ssfsdfdsdgasgsdsdffdf' => 'blogcomments#do_m_blogcomments_reply'
  match 'ggfsdfdssdsdffsddffdf' => 'notecomments#do_m_notecomments_reply'

  get 'latest_attention' => 'blogs#latest_attention'
  get 'hotest' => 'blogs#hotest'
  get 'latest' => 'blogs#latest'

  resources :memoirs do
    resources :memoircomments
  end

  resources :posts do
    resources :postcomments
  end

  match 'following' => 'follows#following'
  match 'followers' => 'follows#followers'
  
  match 'photos/modify' => 'photos#modify'
  match 'customize' => 'customizes#index'
 

  get 'help' => 'users#help'

  match 'recommend_blog' => 'recommend#blog'
  match 'recommend_note' => 'recommend#note'
  match 'recommend_photo' => 'recommend#photo'
  match 'recommend_memoir' => 'recommend#memoir'
  match 'like_post_comment' => 'postcomments#like'
  match 'like_blog_comment' => 'blogcomments#like'
  match 'like_note_comment' => 'notecomments#like'
  match 'like_photo_comment' => 'photocomments#like'
  match 'like_memoir_comment' => 'memoircomments#like'
  get 'portal_show_more' => 'home#portal_show_more'
  

  match 'recommend/modify_note' => 'recommend#modify_note'
  match 'recommend/modify_blog' => 'recommend#modify_blog'
  match 'recommend/modify_photo' => 'recommend#modify_photo'
  match 'recommend/modify_memoir' => 'recommend#modify_memoir'

  match 'editor_blog' => 'editor#blog'
  match 'editor_note' => 'editor#note'

  match 'society_admin' => 'groups#admin'
  match 'admin' => 'admin/home#index'

  match 'register' => 'users#new'
  match 'login' => 'login#to_login'
  match 'login/login'
  match 'login/member_login'
  match 'login/bind_weibo_login'
  match 'login/bind_qq_login'

  match 'like' => 'like#index'
  match 'now' => 'now#index'
  match 'editor' => 'editor#index'

  match 'follow_me' => 'follows#follow_me'
  match 'unfollow' => 'follows#unfollow_me'

  match 'edit_memoirs' => 'memoirs#edit'
  get 'edit_profile' => 'users#edit'
  get 'edit_about' => 'groups#edit_about'
  get 'select_albums' => 'albums#select_albums'
  get 'select_photos/:album_id' => 'albums#select_photos'
  get 'tags/:name' => 'tags#show'
  get 'tags' => 'tags#index'
  get 'click_show_blog' => 'blogs#click_show_blog'
  get 'click_show_note' => 'notes#click_show_note'

  get 'love-zhangtingting' => 'blogs#lovezhangtingting'

  get 'edit_password' => 'users#edit_password'
  match 'update_password' => 'users#update_password'
  match 'update_signature' => 'users#update_signature'
  match 'update_domain' => 'users#update_domain'

  get 'weibo_connect' => 'weibo#connect'
  get 'weibo_callback' => 'weibo#callback'
  get 'weibo_account' => 'weibo#weibo_account'
  get 'cancel_weibo_bind' => 'weibo#cancel_weibo_bind'
  match 'weibo_create_account' => 'weibo#create_account'

  get 'qq_connect' => 'qq#connect'
  get 'qq_callback' => 'qq#callback'
  get 'qq_account' => 'qq#qq_account'
  get 'cancel_qq_bind' => 'qq#cancel_qq_bind'
  match 'qq_create_account' => 'qq#create_account'
  

  
  get 'logout' => 'home#logout'
  get 'autobiography' => 'memoirs#index'
  get 'autobiographies' => 'memoirs#portal'
  
  
  
  namespace :admin do
    
    resources :users,:notes,:blogs

    match 'profile' => 'users#edit'
  end
  match 'profile' => 'users#show'
  match 'edit_profile' => 'users#edit'

  root :to => 'home#index'

  get 'notice' => 'home#notice'
  get 'upload_photo' => 'photos#m_new'
  match 'm_upload_photo' => 'photos#m_upload_photo'
  match 'm_update_photo' => 'photos#m_update_photo'
  match 'create_letter' => 'letters#create_letter'

  get 'my' => 'my/home#index'

  get 'new_function_email'  => 'mails#new_function_email'
  get 'note_21days_email'  => 'mails#note_21days_email'

  get 'update_follow_count'  => 'follows#update_follow_count'
  
  

  

  match '*a', :to => 'errors#routing'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController

  layout 'help'

  def index
    
  end
  
end

app/controllers/my/home_controller.rb
class My::HomeController < My::BaseController

  layout 'help'

  def index
  end
  
end

app/views/home/_photo_content.html.slim
- photo = @photo
- album = photo.album
- user = album.user
.photo_portal
  a.photolst_photo href=(site(user) + album_photo_path(photo.album, photo)) target='_blank'
    = image_tag(photo.avatar.square.url, title: photo.description.to_s[0..43], width: PHOTO_SQUARE_SIZE, height: PHOTO_SQUARE_SIZE)
  br
  .pl
    = link_to user.name, site(user), target: '_blank'
    | :
    = link_to album.name, site(user) + album_path(album), target: '_blank'

app/views/home/_photo_square_portal.html.slim
.photolst.clearfix
  - @all_photos.each_with_index do |item, i|
    - break if i==8
    - if item.is_a?(Photo)
      - @photo = item
    - elsif item.is_a?(Rphoto)
      - @photo = item.photo
    = render 'photo_content'

app/views/home/_photo_square_user.html.slim
- cache "user_home_photos_#{@user.id}" do
  - photos = Photo.where(album_id: @user.albums).includes(:album).limit(5).order('id desc')
  - photos.each do |photo|
    .photo_user
      a.photolst_photo href=album_photo_path(photo.album, photo)
        = image_tag(photo.avatar.square.url, title: photo.description.to_s[0..43], width: PHOTO_SQUARE_SIZE, height: PHOTO_SQUARE_SIZE)
  - unless photos.blank?
    .clear

app/views/home/_portal_article.html_not_use.slim
#wrapper
  #content
    - if flash[:notice]
      #notice= flash[:notice]
    = render 'shared/columns_navigation'
    .grid-13-11.clearfix
      .left
        - @all.each do |item|
          .topic-content2
            - user = item.user
            .user-face
              a href=site(user) target='_blank'
                = image_tag(user.avatar.thumb.url)
            .topic-doc2
              span.x.pl20
                = s_link_to item
              - cc = item.comments_count
              -if cc>0
                span.b.red.rr
                  = cc
              br
              span.b.pl20
                | 作者:&nbsp;
                = link_to user.name, site(user), target: '_blank'
              span.c.rr
                = item.created_at.strftime t'date_without_year'
              br
              span.b.pl20
                = text_it_pure(item.content)[0..98]
                | ......#{s_link_name(t('whole_article'), item)}
      = render 'shared/columns_blogs'
  = render 'shared/footer_portal'
/= render 'search_js'

app/views/home/_user_creation_list.html.slim
- if controller_path=='archives'
  - url_pre = site(@user) + archives_path + "/#{params[:month]}"
- else
  - url_pre = site(@user)
#miniblog
  #db-timeline-hd.clearfix
    ul.menu-list
      - url = link_to t('all'), url_pre
      - if params[:t].nil?
        li.on= url
      - else
        li= url
      - url = link_to t('_note'), url_pre + '?t=note'
      - if params[:t] == 'note'
        li.on= url
      - else
        li= url
      - url = link_to t('_blog'), url_pre + '?t=blog'
      - if params[:t] == 'blog'
        li.on= url
      - else
        li= url
      - url = link_to t('_photo'), url_pre + '?t=photo'
      - if params[:t] == 'photo'
        li.on= url
      - else
        li= url
      - unless controller_path=='archives'
        - url = link_to t('latest_updated'), url_pre + '?t=updated'
        - if params[:t] == 'updated'
          li.on= url
        - else
          li= url
      - url = link_to t('recommend'), url_pre + '?t=recommend'
      - if params[:t] == 'recommend'
        li.on= url
      - else
        li= url
  ul.mbt
    - @all.each do |item|
      - if item.is_a?(Note)
        - unless params[:t] == 'updated' and item.updated_at < item.created_at + 1.day
          - user = @user
          li.mbtr
            span.gray.b
              | 发日记 #{link_to item.title, note_path(item), target: '_blank'}#{recommended_char if @rnids.include? item.id}&nbsp;
            - n = photos_count item.content
            - if n==1
              .npad
                .ll
                  = thumb_here item
            - elsif item.title.to_s!=''
              br
            span.inq
              = summary_comment(item, 140)
              - if n>1
                = thumbs_here(item, 3)
              - else
                br
            span.gray
              = article_time item
            - if item.user_id == session[:id]
              | &nbsp;#{link_to t('edit'), edit_note_path(item), target: '_blank'}&nbsp;#{link_to t('delete'), item, confirm: t('confirm.delete'), method: :delete}
            = note_read_comment_recommend item
      - elsif item.is_a?(Blog)
        - unless params[:t] == 'updated' and item.updated_at < item.created_at + 1.day
          - user = @user
          li.mbtr
            span.gray.b
              | 发表作品《#{link_to item.title, blog_path(item), target: '_blank'}》#{recommended_char if @rbids.include? item.id}
            br
            - n = photos_count item.content
            - if n==1
              .npad
                .ll
                  = thumb_here item
            span.inq
              = summary_comment(item, 180)
              - if n>1
                = thumbs_here(item, 3)
              - else
                br
            span.gray
              = article_time item
            - if item.user_id == session[:id]
              | &nbsp;#{link_to t('edit'), edit_blog_path(item), target: '_blank'}
            = blog_read_comment_recommend item
      - elsif item.is_a?(Photo)
        - album = item.album
        - user = @user
        - avatar = item.avatar
        li.mbtr
          .npad
            .ll
              a id='photo_#{item.id}' href='javascript:;' onclick="switchPhoto('photo_#{item.id}', '#{avatar.url}', '#{avatar.thumb.url}')" title='点击放大'
                = image_tag(avatar.thumb.url)
          span.inq
            span.gray 上传照片到&nbsp;
            = link_to album.name, album_path(album), target: '_blank'
            br
            - unless item.description.to_s==''
              = item.description
              | &nbsp;
            span.gray
              = fresh_time item.created_at
            br
            | #{recommend_etc item}&nbsp;#{link_to "#{t('comment')}#{item.comments_count==0 ? '' : '(' + item.comments_count.to_s + ')' }", "#{album_photo_path(album, item)}#comments", target: '_blank'}
      - elsif item.is_a?(Rnote)
        - note = item.note
        - user = note.user
        li.mbtl
          = user_pic user
        li.mbtr
          span.gray.b
            = link_to user.name, site(user), target: '_blank'
            |  发日记 #{link_to note.title, site(user) + note_path(note), target: '_blank'}&nbsp;
          - n = photos_count note.content
          - if n==1
            .npad
              .ll
                = thumb_here note
          - elsif note.title.to_s!=''
            br
          span.inq
            = summary_comment_portal(note, 150)
            = user_said item.body
            - if n>1
              = thumbs_here(note, 3)
            - else
              br
          span.gray
            = fresh_time item.created_at
          = note_read_comment_recommend_user note
      - elsif item.is_a?(Rblog)
        - blog = item.blog
        - user = blog.user
        li.mbtl
          = user_pic user
        li.mbtr          
          span.gray.b
            = link_to user.name, site(user), target: '_blank'
            |  发表作品 《#{link_to blog.title, site(blog.user) + blog_path(blog), target: '_blank'}》
          br
          - n = photos_count blog.content
          - if n==1
            .npad
              .ll
                = thumb_here blog
          span.inq
            = summary_comment_portal(blog, 190)
            = user_said item.body
            - if n>1
              = thumbs_here(blog, 3)
            - else
              br
          span.gray
            = fresh_time item.created_at
          = blog_read_comment_recommend_user blog
      - elsif item.is_a?(Rphoto)
        - photo = item.photo
        - album = photo.album
        - user = album.user
        - avatar = photo.avatar
        li.mbtl
          = user_pic user
        li.mbtr
          .npad
            .ll
              a id='rphoto_#{photo.id}' href='javascript:;' onclick="switchPhoto('rphoto_#{photo.id}', '#{avatar.url}', '#{avatar.thumb.url}')" title='点击放大'
                = image_tag(avatar.thumb.url)
          span.inq
            span.gray
              = link_to user.name, site(user), target: '_blank'
              span.gray  上传照片到&nbsp;
              = link_to album.name, site(user) + album_path(album), target: '_blank', title: '进入该影集查看照片'
            br
            - unless photo.description.nil?
              = photo.description
              | &nbsp;
            span.gray
              = fresh_time item.created_at
            = user_said item.body
            br
            | #{recommend_etc photo}&nbsp;#{link_to "#{t('comment')}#{photo.comments_count==0 ? '' : '(' + photo.comments_count.to_s + ')' }", "#{album_photo_path(photo.album, photo)}#comments", target: '_blank'}
      - elsif item.is_a?(Memoir)
        li.mbtr
          span.gray.b
            | 更新自传 #{link_to item.title, autobiography_path, target: '_blank'}&nbsp;
          br
          span.inq
            = summary_no_comments(item, 200)
            = thumbs_here(item, 3)
            span.gray
              = article_time item
            - if item.user_id == session[:id]
              | &nbsp;#{link_to t('edit'), edit_memoirs_path, target: '_blank'}

app/views/home/_user_title.html.slim
- case params[:t]
- when 'note'
  = title t('ss_home_page_note', w: @user.name)
- when 'blog'
  = title t('ss_home_page_blog', w: @user.name)
- when 'photo'
  = title t('ss_home_page_photo', w: @user.name)
- when 'updated'
  = title t('ss_home_page_updated', w: @user.name)
- when 'recommend'
  = title t('ss_home_page_recommend', w: @user.name)
- else
  = title t('ss_home_page', w: @user.name, s: site_name)

app/views/home/index.html.slim
= title t_t'seotitle'
= metadesc t_t'metadesc'

app/views/home/notice.html.slim
- if flash[:notice]
  #notice = flash[:notice]

app/views/home/user.html.slim
= render 'user_title'
= metadesc meta_desc_user
= render 'photo_square_user'
= render 'user_creation_list'